### ISSUE TITLE
Sanity check metrics computations

### ISSUE THREAD

**Issue by gsel9** [daanknoors/crn-synth#23]
**Metrics**
Although we compute a whole bunch in `crnsynth/evaluation/reports.py`, The metrics we actually care about are:

*stats*
- jensenshannon_dist $\checkmark$
- ks_test $\checkmark$
- contingency_similarity_score $\checkmark$
- cox_beta_augmented_score (custom metric in crnsynth/evaluation/custom_similarity_metrics) $\checkmark$
- median_survival_augmented_score (custom metric in crnsynth/evaluation/custom_similarity_metrics) $\checkmark$
- predicted_median_survival_augmented_score (custom metric in crnsynth/evaluation/custom_similarity_metrics) $\checkmark$
- survival_curves_distance_augmented_score (custom metric in crnsynth/evaluation/custom_similarity_metrics) $\checkmark$

*performance*
- linear_model
- xgb
- feat_rank_distance

*detection*
- detection_xgb $\checkmark$

*privacy*
- nearest_neighbor_distance_ratio (custom metric in crnsynth/evaluation/custom_privacy_metrics) $\checkmark$
- cap_categorical_score (custom metric in crnsynth/evaluation/custom_privacy_metrics) $\checkmark$
- distance_closest_record (custom metric in crnsynth/evaluation/custom_privacy_metrics) $\checkmark$

**Input data**
The different metric categories have different input datasets. This is defined in crnsynth/evaluation/measure_evaluation. Also see the attached screenshot for this.
![Screenshot 2024-01-19 at 14 39 45](https://github.com/daanknoors/crn-synth/assets/20422814/5a768da5-09c5-41d5-9e92-4ca1534038f0)
Note that the augmented data is [active-arm, control arm training set]. For privacy metrics, the idea is to have a hold-out set available that (hopefully) match the data withheld from synthetization. 

**Expectations**
We have two baseline models, which by my understanding is 
- dummy: Returns the original dataset. This means we expect this to be the strongest performer for all metrics except privacy where it should be the poorest. Also, variance across different runs should be zero here.  
- uniform: Returns a random sample from each of the columns of the original dataset. We expect this to be the poorest performer for all metrics except privacy where it should be the strongest. If this generator relies on a random seed, we should see variance in the performance estimates for different seeds.

**Issues**
- Sometimes a generator performs better than dummy
- Sometimes a generator perform poorer than uniform 
- The generalization option appears to improve results for stats metrics, although data binning removes some of the original information in the data 

**Moving forward**
Create a small test suite for a few generators including the baselines and trackback the errors starting from the results of metrics computations.

**Comment by gsel9** [comment]
**Note to self**: Will add boxplots of the current results to show which metrics seems ok and which are giving unexpected results

**Comment by daanknoors** [comment]
Regarding the input data:

- For sanity, stats and detection: we can use the full synth dataset instead of train - since we don't make a distinction. Probably wont have too much effect but still. However, does mean that real (train) and synth will have different sizes. 
- Also good to check for all metrics if they make splits within. For example, if we are are passing X_gt.train() and in the metric it's split again in train and test, then we should have just passed the full X_gt.

**Comment by gsel9** [comment]
Just and fyi: we adopted from scity to do 
```
eval_cnt = min(
            len(X_gt.train()),
            len(X_syn.train()),
            len(X_gt_aug.train()),
            len(X_syn_aug.train()),
        )

...

 _X_gt.sample(eval_cnt),
 _X_syn.sample(eval_cnt),
```
This means we resample the datasets to have the same number of obs (eval_cnt) before we compute the metrics

**Comment by daanknoors** [comment]
Hm good idea! It could indeed be good to ensure all have the same number of samples.

The only caveat I see is that sampling can give extra variance in results. In case you happen to sample more outliers in one run over another, your results will be different. But hopefully we control for that by reporting results over different seeds.

**Comment by gsel9** [comment]
For custom stats metrics (note to self): An implementation sanity check is that dummy generator gets (almost) perfect score
